service:
  golangci-lint-version: 1.52.2

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
#    - depguard # internal中不含外部依赖 go mod vendor
    - dogsled
    - errcheck
#    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - whitespace

#issues:
#  exclude-rules:
#    - path: internal
#      text: "123"
#      linters:
#        - scopelint

run:
  concurrency: 16
  tests: true
  skip-dirs:
    - vendor
    - main
  allow-parallel-runners: true
