app:
  name: go-maxms
  version: 0.1
  domain: http://127.0.0.1:9001
  enabled:
    rsa: false
    vault: true
  white_list:
    -
      name: frontend
      domain: http://127.0.0.1:9100

lib:
  log:
    level: debug # trace << debug << info << warn << error << fatal << panic
    format: json # text
    color: true
    file_name: app.log
  vault:
    address: http://127.0.0.1:8200
  gin:
    run_mode: debug # debug test release
  db:
    type: mysql
    debug: false
    max_life_time: 8192
    max_open_conns: 100000
    max_idle_conns: 1000
    host: 127.0.0.1
    port: 3306
    name: go_maxms
    params: charset=utf8mb4&parseTime=True&loc=Local
    username: root
    password: 123456

server:
  host: 127.0.0.1
  port: 9200
  base_url: /
  read_timeout: 5 # seconds
  write_timeout: 10
  idle_timeout: 15
  shutdown_timeout: 10

downstream:
  -
    name: go-maxms-be
    host: 127.0.0.1
    port: 9300
