app:
  name: go-maxms
  version: 0.1
  domain: liuzhaomax.cn
  enabled:
    rsa: false # rsa和vault有关联关系
    vault: true
    signature: true # signature默认依赖于redis
  white_list:
    -
      name: frontend
      domain: http://127.0.0.1:9100

lib:
  log:
    level: debug # trace << debug << info << warn << error << fatal << panic
    format: text # text json
    color: true
    file_path: ./log
    file_name: app.log
  vault:
    address: http://127.0.0.1:8200
  gin:
    run_mode: debug # debug test release
  db:
    type: mysql
    debug: true
    max_life_time: 8192
    max_open_conns: 100000
    max_idle_conns: 1000
    host: 127.0.0.1
    port: 3306
    name: go_maxms
    params: charset=utf8mb4&parseTime=True&loc=Local
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
  etcd:
    dial_timeout: 5
    dial_keep_alive_time: 5
    dial_keep_alive_timeout: 5
    endpoint:
      host: 127.0.0.1
      port: 2379
  consul:
    timeout: 3s
    interval: 30s
    deregister_after: 5s
    endpoint:
      host: 127.0.0.1
      port: 8500
  jaeger:
    endpoint:
      host: 127.0.0.1
      port: 6831

server:
  protocol: http
  host: 127.0.0.1
  port: 9999
  base_url: /
  read_timeout: 5 # seconds
  write_timeout: 10
  idle_timeout: 15
  shutdown_timeout: 10

downstream:
  -
    name: go-maxms-be
    host: 127.0.0.1
    port: 9300
