// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/liuzhaomax/go-maxms/internal/api"
	"github.com/liuzhaomax/go-maxms/internal/core"
	"github.com/liuzhaomax/go-maxms/internal/middleware"
	"github.com/liuzhaomax/go-maxms/internal/middleware/auth"
	"github.com/liuzhaomax/go-maxms/internal/middleware/reverse_proxy"
	"github.com/liuzhaomax/go-maxms/internal/middleware/tracing"
	"github.com/liuzhaomax/go-maxms/internal/middleware/validator"
	business2 "github.com/liuzhaomax/go-maxms/src/api_user/business"
	"github.com/liuzhaomax/go-maxms/src/api_user/handler"
	model2 "github.com/liuzhaomax/go-maxms/src/api_user/model"
	"github.com/liuzhaomax/go-maxms/src/api_user_rpc/business"
	"github.com/liuzhaomax/go-maxms/src/api_user_rpc/model"
)

// Injectors from wire.go:

func InitInjector() (*Injector, func(), error) {
	db, cleanup, err := core.InitDB()
	if err != nil {
		return nil, nil, err
	}
	modelUser := &model.ModelUser{
		DB: db,
	}
	trans := &core.Trans{
		DB: db,
	}
	client, cleanup2, err := core.InitRedis()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	logger := core.InitLogrus()
	coreLogger := &core.Logger{
		Logger: logger,
	}
	response := &core.Response{
		Logger: coreLogger,
	}
	businessUser := &business.BusinessUser{
		Model: modelUser,
		Tx:    trans,
		Redis: client,
		IRes:  response,
	}
	engine := core.InitGinEngine()
	authAuth := &auth.Auth{
		Logger: coreLogger,
		Redis:  client,
	}
	validatorValidator := &validator.Validator{
		Logger: coreLogger,
		Redis:  client,
	}
	configuration := core.InitTracer()
	tracingTracing := &tracing.Tracing{
		Logger:       coreLogger,
		TracerConfig: configuration,
	}
	reverseProxy := &reverse_proxy.ReverseProxy{
		Logger:      coreLogger,
		RedisClient: client,
	}
	middlewareMiddleware := &middleware.Middleware{
		Auth:         authAuth,
		Validator:    validatorValidator,
		Tracing:      tracingTracing,
		ReverseProxy: reverseProxy,
	}
	modelModelUser := &model2.ModelUser{
		DB: db,
	}
	businessBusinessUser := &business2.BusinessUser{
		Model: modelModelUser,
		Tx:    trans,
		Redis: client,
	}
	rocketMQ := &core.RocketMQ{}
	handlerUser := &handler.HandlerUser{
		Business:    businessBusinessUser,
		Logger:      coreLogger,
		Res:         response,
		RocketMQSet: rocketMQ,
	}
	registry := core.InitPrometheusRegistry()
	apiHandler := &api.Handler{
		Middleware:         middlewareMiddleware,
		HandlerUser:        handlerUser,
		PrometheusRegistry: registry,
	}
	injector := &Injector{
		RPCService: businessUser,
		Engine:     engine,
		Handler:    apiHandler,
		DB:         db,
		Redis:      client,
	}
	return injector, func() {
		cleanup2()
		cleanup()
	}, nil
}
