// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/liuzhaomax/go-maxms-template-me/internal/api"
	"github.com/liuzhaomax/go-maxms-template-me/internal/core"
	"github.com/liuzhaomax/go-maxms-template-me/src/handler"
)

// Injectors from wire.go:

func InitInjector() (*Injector, error) {
	hData := &handler.HData{}
	apiHandler := &api.Handler{
		HandlerData: hData,
	}
	engine := core.InitGinEngine(apiHandler)
	injector := &Injector{
		Engine:  engine,
		Handler: apiHandler,
	}
	return injector, nil
}
