name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest

    - name: Set up Go
      uses: actions/setup-go@latest
      with:
        go-version: 1.21

    - name: Build
      run: |
        export GO111MODULE=on
        go build -v ./...

#    - name: Test
#      run: go test -v ./...
